# Site settings
title: Schule Online
email: schule@mrfiedler.de
#description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://mrfiedler.de"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
#markdown: kramdown
markdown: CommonMark
permalink: pretty
